CREATE TABLE OSOBA
(
	ID INTEGER PRIMARY KEY,
	IME VARCHAR(20) NOT NULL,
	PREZIME VARCHAR (20) NOT NULL,
	JMBG VARCHAR(13) NOT NULL UNIQUE
);

CREATE TABLE OPERATER
(
	OSOBA_ID INTEGER PRIMARY KEY REFERENCES OSOBA(ID),
	DATUM_RODJENJA DATE NOT NULL,
	DATUM_ZAPOSLJENJA DATE NOT NULL
);


CREATE TABLE KORISNIK
(
	OSOBA_ID INTEGER PRIMARY KEY REFERENCES OSOBA(ID),
	DATUM_REGISTRACIJE DATE NOT NULL
);


CREATE TABLE VOZILO
(
	ID INTEGER PRIMARY KEY,
	MARKA VARCHAR(30),
	TIP CHAR(1),
	REGISTARSKA_TABLICA VARCHAR(10) NOT NULL,
	KORISNIK_ID INTEGER REFERENCES KORISNIK(ID)
);

CREATE TABLE PARKING
(
	ID INTEGER PRIMARY KEY,
	SPRAT NUMBER(2) NOT NULL,
	BROJ NUMBER(3) NOT NULL,
	VOZILO_ID INTEGER REFERENCES VOZILO(ID),
	A_FLAG NUMBER(1) DEFAULT 0,
	B_FLAG NUMBER(1) DEFAULT 1,
	C_FLAG NUMBER(1) DEFAULT 0,
    CHECK(A_FLAG IN(1,0)),
    CHECK(B_FLAG IN(1,0)),
    CHECK(C_FLAG IN(1,0))
);

CREATE TABLE PRETPLATNA_KARTICA
(
	ID INTEGER PRIMARY KEY,
	VAZI_OD DATE NOT NULL,
	VAZI_DO DATE NOT NULL,
	KORISNIK_ID INTEGER REFERENCES KORISNIK(ID) NOT NULL
);

CREATE TABLE POJEDINACNA_KARTICA
(
	ID INTEGER PRIMARY KEY,
	VAZI_OD DATE NOT NULL,
	VAZI_DO DATE NOT NULL,
	VREME_NAPUSTANJA DATE,
	VOZILO_ID INTEGER REFERENCES VOZILO(ID) NOT NULL,
	PARKING_ID INTEGER REFERENCES PARKING(ID) NOT NULL,
	OPERATER_ID INTEGER REFERENCES OPERATER(ID) NOT NULL
);

CREATE TABLE REZERVACIJA
(
	ID INTEGER PRIMARY KEY,
	VAZI_OD DATE NOT NULL,
	VAZI_DO DATE NOT NULL,
	PARKING_ID INTEGER REFERENCES PARKING(ID) NOT NULL,
	KARTICA_ID INTEGER REFERENCES PRETPLATNA_KARTICA(ID) NOT NULL
);

CREATE TABLE NEDELJA
(
	ID INTEGER PRIMARY KEY,
	POCETAK_NEDELJE DATE,
	KONTROLER_ID INTEGER REFERENCES OPERATER(ID) NOT NULL,
	PRVA_SMENA_ID INTEGER REFERENCES OPERATER(ID) NOT NULL,
	DRUGA_SMENA_ID INTEGER REFERENCES OPERATER(ID) NOT NULL,
	TRECA_SMENA_ID INTEGER REFERENCES OPERATER(ID) NOT NULL
);


CREATE SEQUENCE  "OSOBA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER NOCYCLE;
CREATE SEQUENCE  "VOZILO_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER NOCYCLE;
CREATE SEQUENCE  "PARKING_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER NOCYCLE;
CREATE SEQUENCE  "PRETPLATNA_KARTICA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER NOCYCLE;
CREATE SEQUENCE  "REZERVACIJA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER NOCYCLE;
CREATE SEQUENCE  "NEDELJA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER NOCYCLE;
CREATE SEQUENCE  "POJEDINACNA_KARTICA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER NOCYCLE;

  

 CREATE OR REPLACE TRIGGER "OSOBA_AUTO_PK" 
    BEFORE INSERT
    ON OSOBA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT OSOBA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

ALTER TRIGGER "OSOBA_AUTO_PK" ENABLE;

/



CREATE OR REPLACE TRIGGER "VOZILO_AUTO_PK" 
    BEFORE INSERT
    ON VOZILO
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT VOZILO_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "VOZILO_AUTO_PK" ENABLE;

/

  CREATE OR REPLACE TRIGGER "PARKING_AUTO_PK" 
    BEFORE INSERT
    ON PARKING
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT PARKING_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

ALTER TRIGGER "PARKING_AUTO_PK" ENABLE;

/

  CREATE OR REPLACE TRIGGER "POJEDINACNA_KARTICA_AUTO_PK" 
    BEFORE INSERT
    ON POJEDINACNA_KARTICA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT POJEDINACNA_KARTICA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

ALTER TRIGGER "POJEDINACNA_KARTICA_AUTO_PK" ENABLE;

/


  CREATE OR REPLACE TRIGGER "PRETPLATNA_KARTICA_AUTO_PK" 
    BEFORE INSERT
    ON PRETPLATNA_KARTICA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT PRETPLATNA_KARTICA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

ALTER TRIGGER "PRETPLATNA_KARTICA_AUTO_PK" ENABLE;

/
  CREATE OR REPLACE TRIGGER "REZERVACIJA_AUTO_PK" 
    BEFORE INSERT
    ON REZERVACIJA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT REZERVACIJA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

ALTER TRIGGER "REZERVACIJA_AUTO_PK" ENABLE;

/

  CREATE OR REPLACE TRIGGER "NEDELJA_AUTO_PK" 
    BEFORE INSERT
    ON NEDELJA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT NEDELJA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

ALTER TRIGGER "NEDELJA_AUTO_PK" ENABLE;

/

 -------------------------------------------------------------------------
 alter session set nls_date_format = 'dd/MON/yyyy hh24:mi';   -- TREBA DA SE UNESE DA BI SE POSTAVILO I DATUM I VEREME

 /

 alter session set NLS_TIMESTAMP_FORMAT = 'HH24:MI';   -- za podesavanje formata timestamp 
 
 --DODAVANJE U TABELU OPERATER
 
INSERT INTO OPERATER(IME,PREZIME,JMBG,DATUM_RODJENJA,DATUM_ZAPOSLJENJA) VALUES ('Ivan','Markovic','1231231231231',TO_DATE('22/APR/1992', 'DD/MON/YYYY'), TO_DATE('12/APR/2019', 'DD/MON/YYYY'));

INSERT INTO OPERATER(IME,PREZIME,JMBG,DATUM_RODJENJA,DATUM_ZAPOSLJENJA) VALUES ('Marko','Jankovic','1235671231231',TO_DATE('02/JAN/1988', 'DD/MON/YYYY'), TO_DATE('14/APR/2019', 'DD/MON/YYYY'));


--dodavanje u tableu KORISNIK

INSERT INTO KORISNIK(OSOBA_ID, DATUM_REGISTRACIJE) VALUES (1, TO_DATE('20/APR/2019 12:00', 'DD/MON/YYYY HH24:MI'));
INSERT INTO KORISNIK(OSOBA_ID, DATUM_REGISTRACIJE) VALUES (2, TO_DATE('05/APR/2019 12:00', 'DD/MON/YYYY HH24:MI'));
INSERT INTO KORISNIK(OSOBA_ID, DATUM_REGISTRACIJE) VALUES (3, TO_DATE('03/APR/2019 12:00', 'DD/MON/YYYY HH24:MI'));
INSERT INTO KORISNIK(OSOBA_ID, DATUM_REGISTRACIJE) VALUES (4, TO_DATE('10/APR/2019 12:00', 'DD/MON/YYYY HH24:MI'));
INSERT INTO KORISNIK(OSOBA_ID, DATUM_REGISTRACIJE) VALUES (5, TO_DATE('01/APR/2019 12:00', 'DD/MON/YYYY HH24:MI'));

--dodavanje u tabelu VOZILO
INSERT INTO VOZILO(MARKA, TIP, REGISTARSKA_TABLICA, KORISNIK_ID) VALUES ('Purple Lamborghini', 'B', 'PK 027-44', 1);

--dodavanje u tabelu pretplatna kartica
INSERT INTO PRETPLATNA_KARTICA(VAZI_OD, VAZI_DO, KORISNIK_ID) VALUES (TO_DATE('20/APR/2019', 'DD/MON/YYYY'), TO_DATE('20/MAY/2019', 'DD/MON/YYYY'), 1);
INSERT INTO PRETPLATNA_KARTICA(VAZI_OD, VAZI_DO, KORISNIK_ID) VALUES (TO_DATE('05/APR/2019', 'DD/MON/YYYY'), TO_DATE('05/MAY/2019', 'DD/MON/YYYY'), 2);
INSERT INTO PRETPLATNA_KARTICA(VAZI_OD, VAZI_DO, KORISNIK_ID) VALUES (TO_DATE('03/APR/2019', 'DD/MON/YYYY'), TO_DATE('03/MAY/2019', 'DD/MON/YYYY'), 3);
INSERT INTO PRETPLATNA_KARTICA(VAZI_OD, VAZI_DO, KORISNIK_ID) VALUES (TO_DATE('10/APR/2019', 'DD/MON/YYYY'), TO_DATE('10/MAY/2019', 'DD/MON/YYYY'), 4);
INSERT INTO PRETPLATNA_KARTICA(VAZI_OD, VAZI_DO, KORISNIK_ID) VALUES (TO_DATE('01/APR/2019', 'DD/MON/YYYY'), TO_DATE('01/MAY/2019', 'DD/MON/YYYY'), 5);

--DODAVANJE U TABELU PARKING
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (1, 1, 0, 1, 0);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (1, 2, 0, 1, 0);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (1, 3, 1, 1, 1);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (1, 4, 1, 1, 1);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (1, 5, 0, 1, 1);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (1, 6, 0, 1, 0);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (1, 7, 0, 1, 0);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (2, 1, 1, 1, 0);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (2, 2, 0, 1, 0);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (2, 3, 1, 1, 1);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (2, 4, 0, 1, 1);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (2, 5, 0, 1, 0);
INSERT INTO PARKING(SPRAT, BROJ, A_FLAG, B_FLAG, C_FLAG) VALUES (2, 6, 1, 1, 0);
--VOZILO_ID ostaje prazno jer nije ni jedan auto parkiran na njemu (tj. ne pominje se)

--dodavanje u tabelu pojedinacna kartica
--moras da ubacis vozilo (ali samo tip i tablicu posto je za pojedinacnu karticu) pre kartice
INSERT INTO VOZILO(TIP, REGISTARSKA_TABLICA) VALUES ('B', 'LE 456 22');

INSERT INTO POJEDINACNA_KARTICA(VAZI_OD, VAZI_DO, VREME_NAPUSTANJA, VOZILO_ID, PARKING_ID, OPERATER_ID) 
VALUES (TO_DATE('19/APR/2019 15:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('29/APR/2019 12:00', 'DD/MON/YYYY HH24:MI'), NULL , 6, 9, 5);
INSERT INTO POJEDINACNA_KARTICA(VAZI_OD, VAZI_DO, VREME_NAPUSTANJA, VOZILO_ID, PARKING_ID, OPERATER_ID) 
VALUES (TO_DATE('20/APR/2019 15:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('20/APR/2019 18:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('14/APR/2019 16:30', 'DD/MON/YYYY HH24:MI'), 7, 10, 6);
INSERT INTO POJEDINACNA_KARTICA(VAZI_OD, VAZI_DO, VREME_NAPUSTANJA, VOZILO_ID, PARKING_ID, OPERATER_ID) 
VALUES (TO_DATE('20/APR/2019 12:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('20/APR/2019 14:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('14/APR/2019 13:50', 'DD/MON/YYYY HH24:MI'), 8, 10,7);
INSERT INTO POJEDINACNA_KARTICA(VAZI_OD, VAZI_DO, VREME_NAPUSTANJA, VOZILO_ID, PARKING_ID, OPERATER_ID) 
VALUES (TO_DATE('20/APR/2019 08:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('20/APR/2019 18:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('14/APR/2019 17:36', 'DD/MON/YYYY HH24:MI'), 9, 11, 5);
INSERT INTO POJEDINACNA_KARTICA(VAZI_OD, VAZI_DO, VREME_NAPUSTANJA, VOZILO_ID, PARKING_ID, OPERATER_ID) 
VALUES (TO_DATE('21/APR/2019 15:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('21/APR/2019 22:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('21/APR/2019 21:50', 'DD/MON/YYYY HH24:MI'), 10, 10, 6);


INSERT INTO REZERVACIJE(VAZI_OD, VAZI_DO, PARKING_ID, KARTICA_ID) 

INSERT INTO REZERVACIJA(VAZI_OD, VAZI_DO, PARKING_ID, KARTICA_ID) VALUES (TO_DATE('08:00', 'HH24:MI'), TO_DATE('16:00', 'HH24:MI'), 1, 6);
INSERT INTO REZERVACIJA(VAZI_OD, VAZI_DO, PARKING_ID, KARTICA_ID) VALUES (TO_DATE('13:00', 'HH24:MI'), TO_DATE('21:00', 'HH24:MI'), 2, 7);
INSERT INTO REZERVACIJA(VAZI_OD, VAZI_DO, PARKING_ID, KARTICA_ID) VALUES (TO_DATE('15:00', 'HH24:MI'), TO_DATE('22:00', 'HH24:MI'), 3, 8);
INSERT INTO REZERVACIJA(VAZI_OD, VAZI_DO, PARKING_ID, KARTICA_ID) VALUES (TO_DATE('12:00', 'HH24:MI'), TO_DATE('16:00', 'HH24:MI'), 4, 9);
INSERT INTO REZERVACIJA(VAZI_OD, VAZI_DO, PARKING_ID, KARTICA_ID) VALUES (TO_DATE('13:00', 'HH24:MI'), TO_DATE('20:00', 'HH24:MI'), 5, 5);


--DODAVANJE PODATAKA O NDELJENJI
INSERT INTO NEDELJA(POCETAK_NEDELJE, KONTROLER_ID, PRVA_SMENA_ID, DRUGA_SMENA_ID, TRECA_SMENA_ID) VALUES (TO_DATE('22/APR/2019', 'DD/MON/YYYY'), 1, 1, 4, 3);
